name: VSCode
on:
  workflow_dispatch:

env:
  CFLAGS: "-march=x86-64-v3"
  CXXFLAGS: "-march=x86-64-v3"
  ZSTD_CLEVEL: "19"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fawazahmed0/action-debug-vscode@main
